# Generated by Django 4.2 on 2024-09-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_remove_candidate_id_candidate_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='student_class',
            field=models.IntegerField(default=0),
        ),
    ]
