# Generated by Django 4.2 on 2024-09-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_paid_months',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
