# Generated by Django 4.2 on 2024-09-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_alter_fee_fee_paid_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.IntegerField()),
                ('fee_name', models.CharField(max_length=30)),
                ('fee_value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_paid_months',
            field=models.IntegerField(default=0),
        ),
    ]
